### ISSUE TITLE
PullPush API is now available.

### ISSUE THREAD

**Issue by pullpush-io** [adhesivecheese/chearch#5]
Feel free to visit https://pullpush.io for details.

On a personal note, I would like to add that labelling a project of this scope "vaporware" just because it wasn't out a week after announcement is incredibly toxic. It realise it might have been a microaggresion though so no hard feelings.

**Comment by adhesivecheese** [comment]
This is frankly incredibly premature at this point - you're only offering search of a single subreddit, and your search times are incredibly slow (that six second figure bears out if you're searching a single word, but a 7 word phrase is routinely clocking a 30+ second turnaround in my limited testing). In short, this is not a generally useful resource at this point.

Github issues hardly seem the place for personal notes as response from other venues, but since you've already opened that door: At this point, I stand by what I said (and also, I would argue that [stating my personal suspicion](https://www.reddit.com/r/pushshift/comments/14fm4mt/the_chearch_frontend_has_been_updated_to_use_api/jp35w95/?context=10000) counts as strongly as "labeling", but I digress.)

Storing the existing archives is a trivial matter as long as you've got the money to throw at storage space. Ingesting new content with the API restrictions requires one to be clever, but I haven't seen evidence you're doing that yet. Reasonably speedy search at this scale is a capital H Hard problem, and one that you admit in your documentation that you don't yet have a solution for while you're in your "testing phrase [sic]".

If and when you can use your API to search more than a single subreddit, and if and when you have your search times down to a reasonably tolerable wait, I'd be more than happy for you to reopen this issue.

**Comment by pullpush-io** [comment]
Ok. Thanks for spotting the typo.

I just would like to notify you that I decided, in accordance with your MIT licence, I decided implement this code as a temporary stopgap search for PullPush. Thank you for for your contributions to FOSS software.

In case you find this objectionable (your tone leads me to believe so) we will move on to more advanced software in the future. I picked yours because it is literally an HTML file, so I could push that one out in an hour.

**Comment by adhesivecheese** [comment]
It may surprise you, since you seem to be going out of your way to be a dick to folks, myself included, since you announced your project, but I'm perfectly happy for you to use my code. Hell, point me at the repo and when I get around to patching some of the little bugs that float around chearch I'll be happy to push 'em downstream to you, if they make sense in your fork.

IF pullpush ever gets to a point where it's generally useful, I'll still be happy to integrate it as a backend for chearch, primitive though it may be, despite your incredibly disagreeable behavior. 

Seriously though - it costs nothing to not be the flavor ass you're being right now. You've attempted character assassination, then *insulted the code you've grabbed to use* that I wrote, all because I expressed doubts about the viability of your project. Extraordinary claims require extraordinary evidence. You had made extraordinary claims with nothing to back it up. And while you *might* very well have the bonafides to pull this off, you had, at the time I made my comment, presented zero evidence to the community that you do; it is perfectly reasonable to be skeptical.
